version: '2'
services:
  local:
    build: .
    ports:
      - 8000:8000
      - 9000:9000
    networks:
      gateway:
        aliases:
          - dynamodb_local_admin
  local_mem:
    extends: local
    environment:
      - DYNAMODB_LOCAL_ARGS=-inMemory
networks:
  gateway:
    external: true 
